// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ble_lib/test/descriptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter_ble_lib/flutter_ble_lib.dart' as _i2;
import 'package:flutter_ble_lib/src/_managers_for_classes.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeService_0 extends _i1.SmartFake implements _i2.Service {
  _FakeService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptorWithValue_1 extends _i1.SmartFake
    implements _i2.DescriptorWithValue {
  _FakeDescriptorWithValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptor_2 extends _i1.SmartFake implements _i2.Descriptor {
  _FakeDescriptor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ManagerForDescriptor].
///
/// See the documentation for Mockito's code generation for more information.
class MockManagerForDescriptor extends _i1.Mock
    implements _i3.ManagerForDescriptor {
  MockManagerForDescriptor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Uint8List> readDescriptorForIdentifier(
    _i2.Descriptor? descriptor,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForIdentifier, [
              descriptor,
              transactionId,
            ]),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> writeDescriptorForIdentifier(
    _i2.Descriptor? descriptor,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForIdentifier, [
              descriptor,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [Characteristic].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacteristic extends _i1.Mock implements _i2.Characteristic {
  MockCharacteristic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Service get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakeService_0(this, Invocation.getter(#service)),
          )
          as _i2.Service);

  @override
  String get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#uuid)),
          )
          as String);

  @override
  bool get isReadable =>
      (super.noSuchMethod(Invocation.getter(#isReadable), returnValue: false)
          as bool);

  @override
  bool get isWritableWithResponse =>
      (super.noSuchMethod(
            Invocation.getter(#isWritableWithResponse),
            returnValue: false,
          )
          as bool);

  @override
  bool get isWritableWithoutResponse =>
      (super.noSuchMethod(
            Invocation.getter(#isWritableWithoutResponse),
            returnValue: false,
          )
          as bool);

  @override
  bool get isNotifiable =>
      (super.noSuchMethod(Invocation.getter(#isNotifiable), returnValue: false)
          as bool);

  @override
  bool get isIndicatable =>
      (super.noSuchMethod(Invocation.getter(#isIndicatable), returnValue: false)
          as bool);

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  set isReadable(bool? value) => super.noSuchMethod(
    Invocation.setter(#isReadable, value),
    returnValueForMissingStub: null,
  );

  @override
  set isWritableWithResponse(bool? value) => super.noSuchMethod(
    Invocation.setter(#isWritableWithResponse, value),
    returnValueForMissingStub: null,
  );

  @override
  set isWritableWithoutResponse(bool? value) => super.noSuchMethod(
    Invocation.setter(#isWritableWithoutResponse, value),
    returnValueForMissingStub: null,
  );

  @override
  set isNotifiable(bool? value) => super.noSuchMethod(
    Invocation.setter(#isNotifiable, value),
    returnValueForMissingStub: null,
  );

  @override
  set isIndicatable(bool? value) => super.noSuchMethod(
    Invocation.setter(#isIndicatable, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.Uint8List> read({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#transactionId: transactionId}),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> write(
    _i5.Uint8List? value,
    bool? withResponse, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #write,
              [value, withResponse],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.Uint8List> monitor({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#monitor, [], {#transactionId: transactionId}),
            returnValue: _i4.Stream<_i5.Uint8List>.empty(),
          )
          as _i4.Stream<_i5.Uint8List>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptors() =>
      (super.noSuchMethod(
            Invocation.method(#descriptors, []),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptor(
    String? descriptorUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readDescriptor,
              [descriptorUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_1(
                this,
                Invocation.method(
                  #readDescriptor,
                  [descriptorUuid],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptor(
    String? descriptorUuid,
    _i5.Uint8List? value, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDescriptor,
              [descriptorUuid, value],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_2(
                this,
                Invocation.method(
                  #writeDescriptor,
                  [descriptorUuid, value],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);
}
