// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ble_lib/test/service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter_ble_lib/flutter_ble_lib.dart' as _i2;
import 'package:flutter_ble_lib/src/_internal.dart' as _i7;
import 'package:flutter_ble_lib/src/_managers_for_classes.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCharacteristicWithValue_0 extends _i1.SmartFake
    implements _i2.CharacteristicWithValue {
  _FakeCharacteristicWithValue_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCharacteristic_1 extends _i1.SmartFake
    implements _i2.Characteristic {
  _FakeCharacteristic_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptorWithValue_2 extends _i1.SmartFake
    implements _i2.DescriptorWithValue {
  _FakeDescriptorWithValue_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptor_3 extends _i1.SmartFake implements _i2.Descriptor {
  _FakeDescriptor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeService_4 extends _i1.SmartFake implements _i2.Service {
  _FakeService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Peripheral].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeripheral extends _i1.Mock implements _i2.Peripheral {
  MockPeripheral() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  set name(String? value) => super.noSuchMethod(
    Invocation.setter(#name, value),
    returnValueForMissingStub: null,
  );

  @override
  set identifier(String? value) => super.noSuchMethod(
    Invocation.setter(#identifier, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> connect({
    bool? isAutoConnect = false,
    int? requestMtu = 0,
    bool? refreshGatt = false,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {
              #isAutoConnect: isAutoConnect,
              #requestMtu: requestMtu,
              #refreshGatt: refreshGatt,
              #timeout: timeout,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.PeripheralConnectionState> observeConnectionState({
    bool? emitCurrentValue = false,
    bool? completeOnDisconnect = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#observeConnectionState, [], {
              #emitCurrentValue: emitCurrentValue,
              #completeOnDisconnect: completeOnDisconnect,
            }),
            returnValue: _i4.Stream<_i2.PeripheralConnectionState>.empty(),
          )
          as _i4.Stream<_i2.PeripheralConnectionState>);

  @override
  _i4.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> disconnectOrCancelConnection() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectOrCancelConnection, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> discoverAllServicesAndCharacteristics({
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#discoverAllServicesAndCharacteristics, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Service>> services() =>
      (super.noSuchMethod(
            Invocation.method(#services, []),
            returnValue: _i4.Future<List<_i2.Service>>.value(<_i2.Service>[]),
          )
          as _i4.Future<List<_i2.Service>>);

  @override
  _i4.Future<List<_i2.Characteristic>> characteristics(String? servicedUuid) =>
      (super.noSuchMethod(
            Invocation.method(#characteristics, [servicedUuid]),
            returnValue: _i4.Future<List<_i2.Characteristic>>.value(
              <_i2.Characteristic>[],
            ),
          )
          as _i4.Future<List<_i2.Characteristic>>);

  @override
  _i4.Future<int> rssi({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#rssi, [], {#transactionId: transactionId}),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> requestMtu(int? mtu, {String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestMtu,
              [mtu],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.CharacteristicWithValue> readCharacteristic(
    String? serviceUuid,
    String? characteristicUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readCharacteristic,
              [serviceUuid, characteristicUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.CharacteristicWithValue>.value(
              _FakeCharacteristicWithValue_0(
                this,
                Invocation.method(
                  #readCharacteristic,
                  [serviceUuid, characteristicUuid],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.CharacteristicWithValue>);

  @override
  _i4.Future<_i2.Characteristic> writeCharacteristic(
    String? serviceUuid,
    String? characteristicUuid,
    _i5.Uint8List? value,
    bool? withResponse, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCharacteristic,
              [serviceUuid, characteristicUuid, value, withResponse],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.Characteristic>.value(
              _FakeCharacteristic_1(
                this,
                Invocation.method(
                  #writeCharacteristic,
                  [serviceUuid, characteristicUuid, value, withResponse],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Characteristic>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForCharacteristic(
    String? serviceUuid,
    String? characteristicUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForCharacteristic, [
              serviceUuid,
              characteristicUuid,
            ]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptor(
    String? serviceUuid,
    String? characteristicUuid,
    String? descriptorUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readDescriptor,
              [serviceUuid, characteristicUuid, descriptorUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(
                  #readDescriptor,
                  [serviceUuid, characteristicUuid, descriptorUuid],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptor(
    String? serviceUuid,
    String? characteristicUuid,
    String? descriptorUuid,
    _i5.Uint8List? value, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDescriptor,
              [serviceUuid, characteristicUuid, descriptorUuid, value],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(
                  #writeDescriptor,
                  [serviceUuid, characteristicUuid, descriptorUuid, value],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);

  @override
  _i4.Stream<_i2.CharacteristicWithValue> monitorCharacteristic(
    String? serviceUuid,
    String? characteristicUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #monitorCharacteristic,
              [serviceUuid, characteristicUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Stream<_i2.CharacteristicWithValue>.empty(),
          )
          as _i4.Stream<_i2.CharacteristicWithValue>);
}

/// A class which mocks [ManagerForService].
///
/// See the documentation for Mockito's code generation for more information.
class MockManagerForService extends _i1.Mock implements _i6.ManagerForService {
  MockManagerForService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Characteristic>> characteristicsForService(
    _i2.Service? service,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#characteristicsForService, [service]),
            returnValue: _i4.Future<List<_i2.Characteristic>>.value(
              <_i2.Characteristic>[],
            ),
          )
          as _i4.Future<List<_i2.Characteristic>>);

  @override
  _i4.Future<_i2.CharacteristicWithValue> readCharacteristicForService(
    _i2.Peripheral? peripheral,
    _i7.InternalService? service,
    String? characteristicUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristicForService, [
              peripheral,
              service,
              characteristicUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.CharacteristicWithValue>.value(
              _FakeCharacteristicWithValue_0(
                this,
                Invocation.method(#readCharacteristicForService, [
                  peripheral,
                  service,
                  characteristicUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.CharacteristicWithValue>);

  @override
  _i4.Future<_i2.Characteristic> writeCharacteristicForService(
    _i2.Peripheral? peripheral,
    _i7.InternalService? service,
    String? characteristicUuid,
    _i5.Uint8List? value,
    bool? withResponse,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeCharacteristicForService, [
              peripheral,
              service,
              characteristicUuid,
              value,
              withResponse,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Characteristic>.value(
              _FakeCharacteristic_1(
                this,
                Invocation.method(#writeCharacteristicForService, [
                  peripheral,
                  service,
                  characteristicUuid,
                  value,
                  withResponse,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Characteristic>);

  @override
  _i4.Stream<_i2.CharacteristicWithValue> monitorCharacteristicForService(
    _i2.Peripheral? peripheral,
    _i7.InternalService? service,
    String? characteristicUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#monitorCharacteristicForService, [
              peripheral,
              service,
              characteristicUuid,
              transactionId,
            ]),
            returnValue: _i4.Stream<_i2.CharacteristicWithValue>.empty(),
          )
          as _i4.Stream<_i2.CharacteristicWithValue>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForService(
    _i2.Service? service,
    String? characteristicUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForService, [
              service,
              characteristicUuid,
            ]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptorForService(
    _i2.Service? service,
    String? characteristicUuid,
    String? descriptorUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForService, [
              service,
              characteristicUuid,
              descriptorUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(#readDescriptorForService, [
                  service,
                  characteristicUuid,
                  descriptorUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptorForService(
    _i2.Service? service,
    String? characteristicUuid,
    String? descriptorUuid,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForService, [
              service,
              characteristicUuid,
              descriptorUuid,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(#writeDescriptorForService, [
                  service,
                  characteristicUuid,
                  descriptorUuid,
                  value,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);
}

/// A class which mocks [ManagerForDescriptor].
///
/// See the documentation for Mockito's code generation for more information.
class MockManagerForDescriptor extends _i1.Mock
    implements _i6.ManagerForDescriptor {
  MockManagerForDescriptor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Uint8List> readDescriptorForIdentifier(
    _i2.Descriptor? descriptor,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForIdentifier, [
              descriptor,
              transactionId,
            ]),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> writeDescriptorForIdentifier(
    _i2.Descriptor? descriptor,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForIdentifier, [
              descriptor,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CharacteristicWithValue].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacteristicWithValue extends _i1.Mock
    implements _i2.CharacteristicWithValue {
  MockCharacteristicWithValue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Uint8List get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _i5.Uint8List(0),
          )
          as _i5.Uint8List);

  @override
  set value(_i5.Uint8List? value) => super.noSuchMethod(
    Invocation.setter(#value, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Service get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakeService_4(this, Invocation.getter(#service)),
          )
          as _i2.Service);

  @override
  String get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#uuid)),
          )
          as String);

  @override
  bool get isReadable =>
      (super.noSuchMethod(Invocation.getter(#isReadable), returnValue: false)
          as bool);

  @override
  bool get isWritableWithResponse =>
      (super.noSuchMethod(
            Invocation.getter(#isWritableWithResponse),
            returnValue: false,
          )
          as bool);

  @override
  bool get isWritableWithoutResponse =>
      (super.noSuchMethod(
            Invocation.getter(#isWritableWithoutResponse),
            returnValue: false,
          )
          as bool);

  @override
  bool get isNotifiable =>
      (super.noSuchMethod(Invocation.getter(#isNotifiable), returnValue: false)
          as bool);

  @override
  bool get isIndicatable =>
      (super.noSuchMethod(Invocation.getter(#isIndicatable), returnValue: false)
          as bool);

  @override
  set uuid(String? value) => super.noSuchMethod(
    Invocation.setter(#uuid, value),
    returnValueForMissingStub: null,
  );

  @override
  set isReadable(bool? value) => super.noSuchMethod(
    Invocation.setter(#isReadable, value),
    returnValueForMissingStub: null,
  );

  @override
  set isWritableWithResponse(bool? value) => super.noSuchMethod(
    Invocation.setter(#isWritableWithResponse, value),
    returnValueForMissingStub: null,
  );

  @override
  set isWritableWithoutResponse(bool? value) => super.noSuchMethod(
    Invocation.setter(#isWritableWithoutResponse, value),
    returnValueForMissingStub: null,
  );

  @override
  set isNotifiable(bool? value) => super.noSuchMethod(
    Invocation.setter(#isNotifiable, value),
    returnValueForMissingStub: null,
  );

  @override
  set isIndicatable(bool? value) => super.noSuchMethod(
    Invocation.setter(#isIndicatable, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.Uint8List> read({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#transactionId: transactionId}),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> write(
    _i5.Uint8List? value,
    bool? withResponse, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #write,
              [value, withResponse],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.Uint8List> monitor({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#monitor, [], {#transactionId: transactionId}),
            returnValue: _i4.Stream<_i5.Uint8List>.empty(),
          )
          as _i4.Stream<_i5.Uint8List>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptors() =>
      (super.noSuchMethod(
            Invocation.method(#descriptors, []),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptor(
    String? descriptorUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readDescriptor,
              [descriptorUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(
                  #readDescriptor,
                  [descriptorUuid],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptor(
    String? descriptorUuid,
    _i5.Uint8List? value, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDescriptor,
              [descriptorUuid, value],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(
                  #writeDescriptor,
                  [descriptorUuid, value],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);
}

/// A class which mocks [DescriptorWithValue].
///
/// See the documentation for Mockito's code generation for more information.
class MockDescriptorWithValue extends _i1.Mock
    implements _i2.DescriptorWithValue {
  MockDescriptorWithValue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Uint8List get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _i5.Uint8List(0),
          )
          as _i5.Uint8List);

  @override
  set value(_i5.Uint8List? value) => super.noSuchMethod(
    Invocation.setter(#value, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Characteristic get characteristic =>
      (super.noSuchMethod(
            Invocation.getter(#characteristic),
            returnValue: _FakeCharacteristic_1(
              this,
              Invocation.getter(#characteristic),
            ),
          )
          as _i2.Characteristic);

  @override
  String get uuid =>
      (super.noSuchMethod(
            Invocation.getter(#uuid),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#uuid)),
          )
          as String);

  @override
  _i4.Future<_i5.Uint8List> read({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#transactionId: transactionId}),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> write(_i5.Uint8List? value, {String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [value], {#transactionId: transactionId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
