// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ble_lib/test/test_util/characteristic_generator.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter_ble_lib/flutter_ble_lib.dart' as _i2;
import 'package:flutter_ble_lib/src/_internal.dart' as _i6;
import 'package:flutter_ble_lib/src/_managers_for_classes.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDescriptorWithValue_0 extends _i1.SmartFake
    implements _i2.DescriptorWithValue {
  _FakeDescriptorWithValue_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptor_1 extends _i1.SmartFake implements _i2.Descriptor {
  _FakeDescriptor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ManagerForCharacteristic].
///
/// See the documentation for Mockito's code generation for more information.
class MockManagerForCharacteristic extends _i1.Mock
    implements _i3.ManagerForCharacteristic {
  @override
  _i4.Future<_i5.Uint8List> readCharacteristicForIdentifier(
    _i2.Peripheral? peripheral,
    _i6.InternalCharacteristic? characteristic,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristicForIdentifier, [
              peripheral,
              characteristic,
              transactionId,
            ]),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
            returnValueForMissingStub: _i4.Future<_i5.Uint8List>.value(
              _i5.Uint8List(0),
            ),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> writeCharacteristicForIdentifier(
    _i2.Peripheral? peripheral,
    _i6.InternalCharacteristic? characteristic,
    _i5.Uint8List? value,
    bool? withResponse,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeCharacteristicForIdentifier, [
              peripheral,
              characteristic,
              value,
              withResponse,
              transactionId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.Uint8List> monitorCharacteristicForIdentifier(
    _i2.Peripheral? peripheral,
    _i6.InternalCharacteristic? characteristic,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#monitorCharacteristicForIdentifier, [
              peripheral,
              characteristic,
              transactionId,
            ]),
            returnValue: _i4.Stream<_i5.Uint8List>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.Uint8List>.empty(),
          )
          as _i4.Stream<_i5.Uint8List>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForCharacteristic(
    _i2.Characteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForCharacteristic, [characteristic]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptorForCharacteristic(
    _i2.Characteristic? characteristic,
    String? descriptorUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForCharacteristic, [
              characteristic,
              descriptorUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_0(
                this,
                Invocation.method(#readDescriptorForCharacteristic, [
                  characteristic,
                  descriptorUuid,
                  transactionId,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.DescriptorWithValue>.value(
                  _FakeDescriptorWithValue_0(
                    this,
                    Invocation.method(#readDescriptorForCharacteristic, [
                      characteristic,
                      descriptorUuid,
                      transactionId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptorForCharacteristic(
    _i2.Characteristic? characteristic,
    String? descriptorUuid,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForCharacteristic, [
              characteristic,
              descriptorUuid,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_1(
                this,
                Invocation.method(#writeDescriptorForCharacteristic, [
                  characteristic,
                  descriptorUuid,
                  value,
                  transactionId,
                ]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_1(
                this,
                Invocation.method(#writeDescriptorForCharacteristic, [
                  characteristic,
                  descriptorUuid,
                  value,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);
}
