// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ble_lib/test/src/bridge/lib_core_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter_ble_lib/flutter_ble_lib.dart' as _i2;
import 'package:flutter_ble_lib/src/_internal.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCharacteristicWithValue_0 extends _i1.SmartFake
    implements _i2.CharacteristicWithValue {
  _FakeCharacteristicWithValue_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCharacteristic_1 extends _i1.SmartFake
    implements _i2.Characteristic {
  _FakeCharacteristic_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptorWithValue_2 extends _i1.SmartFake
    implements _i2.DescriptorWithValue {
  _FakeDescriptorWithValue_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDescriptor_3 extends _i1.SmartFake implements _i2.Descriptor {
  _FakeDescriptor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeripheral_4 extends _i1.SmartFake implements _i2.Peripheral {
  _FakePeripheral_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Peripheral].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeripheral extends _i1.Mock implements _i2.Peripheral {
  MockPeripheral() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  set name(String? value) => super.noSuchMethod(
    Invocation.setter(#name, value),
    returnValueForMissingStub: null,
  );

  @override
  set identifier(String? value) => super.noSuchMethod(
    Invocation.setter(#identifier, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> connect({
    bool? isAutoConnect = false,
    int? requestMtu = 0,
    bool? refreshGatt = false,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {
              #isAutoConnect: isAutoConnect,
              #requestMtu: requestMtu,
              #refreshGatt: refreshGatt,
              #timeout: timeout,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.PeripheralConnectionState> observeConnectionState({
    bool? emitCurrentValue = false,
    bool? completeOnDisconnect = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#observeConnectionState, [], {
              #emitCurrentValue: emitCurrentValue,
              #completeOnDisconnect: completeOnDisconnect,
            }),
            returnValue: _i4.Stream<_i2.PeripheralConnectionState>.empty(),
          )
          as _i4.Stream<_i2.PeripheralConnectionState>);

  @override
  _i4.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> disconnectOrCancelConnection() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectOrCancelConnection, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> discoverAllServicesAndCharacteristics({
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#discoverAllServicesAndCharacteristics, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Service>> services() =>
      (super.noSuchMethod(
            Invocation.method(#services, []),
            returnValue: _i4.Future<List<_i2.Service>>.value(<_i2.Service>[]),
          )
          as _i4.Future<List<_i2.Service>>);

  @override
  _i4.Future<List<_i2.Characteristic>> characteristics(String? servicedUuid) =>
      (super.noSuchMethod(
            Invocation.method(#characteristics, [servicedUuid]),
            returnValue: _i4.Future<List<_i2.Characteristic>>.value(
              <_i2.Characteristic>[],
            ),
          )
          as _i4.Future<List<_i2.Characteristic>>);

  @override
  _i4.Future<int> rssi({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#rssi, [], {#transactionId: transactionId}),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> requestMtu(int? mtu, {String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestMtu,
              [mtu],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.CharacteristicWithValue> readCharacteristic(
    String? serviceUuid,
    String? characteristicUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readCharacteristic,
              [serviceUuid, characteristicUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.CharacteristicWithValue>.value(
              _FakeCharacteristicWithValue_0(
                this,
                Invocation.method(
                  #readCharacteristic,
                  [serviceUuid, characteristicUuid],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.CharacteristicWithValue>);

  @override
  _i4.Future<_i2.Characteristic> writeCharacteristic(
    String? serviceUuid,
    String? characteristicUuid,
    _i5.Uint8List? value,
    bool? withResponse, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCharacteristic,
              [serviceUuid, characteristicUuid, value, withResponse],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.Characteristic>.value(
              _FakeCharacteristic_1(
                this,
                Invocation.method(
                  #writeCharacteristic,
                  [serviceUuid, characteristicUuid, value, withResponse],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Characteristic>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForCharacteristic(
    String? serviceUuid,
    String? characteristicUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForCharacteristic, [
              serviceUuid,
              characteristicUuid,
            ]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptor(
    String? serviceUuid,
    String? characteristicUuid,
    String? descriptorUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readDescriptor,
              [serviceUuid, characteristicUuid, descriptorUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(
                  #readDescriptor,
                  [serviceUuid, characteristicUuid, descriptorUuid],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptor(
    String? serviceUuid,
    String? characteristicUuid,
    String? descriptorUuid,
    _i5.Uint8List? value, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDescriptor,
              [serviceUuid, characteristicUuid, descriptorUuid, value],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(
                  #writeDescriptor,
                  [serviceUuid, characteristicUuid, descriptorUuid, value],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);

  @override
  _i4.Stream<_i2.CharacteristicWithValue> monitorCharacteristic(
    String? serviceUuid,
    String? characteristicUuid, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #monitorCharacteristic,
              [serviceUuid, characteristicUuid],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Stream<_i2.CharacteristicWithValue>.empty(),
          )
          as _i4.Stream<_i2.CharacteristicWithValue>);
}

/// A class which mocks [InternalBleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternalBleManager extends _i1.Mock
    implements _i6.InternalBleManager {
  MockInternalBleManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isClientCreated() =>
      (super.noSuchMethod(
            Invocation.method(#isClientCreated, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> createClient({
    String? restoreStateIdentifier,
    _i2.RestoreStateAction? restoreStateAction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClient, [], {
              #restoreStateIdentifier: restoreStateIdentifier,
              #restoreStateAction: restoreStateAction,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroyClient() =>
      (super.noSuchMethod(
            Invocation.method(#destroyClient, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelTransaction, [transactionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> enableRadio({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#enableRadio, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disableRadio({String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#disableRadio, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.BluetoothState> bluetoothState() =>
      (super.noSuchMethod(
            Invocation.method(#bluetoothState, []),
            returnValue: _i4.Future<_i2.BluetoothState>.value(
              _i2.BluetoothState.UNKNOWN,
            ),
          )
          as _i4.Future<_i2.BluetoothState>);

  @override
  _i4.Stream<_i2.BluetoothState> observeBluetoothState({
    bool? emitCurrentValue = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#observeBluetoothState, [], {
              #emitCurrentValue: emitCurrentValue,
            }),
            returnValue: _i4.Stream<_i2.BluetoothState>.empty(),
          )
          as _i4.Stream<_i2.BluetoothState>);

  @override
  _i4.Stream<_i2.ScanResult> startPeripheralScan({
    int? scanMode = 0,
    int? callbackType = 1,
    List<String>? uuids = const [],
    bool? allowDuplicates = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startPeripheralScan, [], {
              #scanMode: scanMode,
              #callbackType: callbackType,
              #uuids: uuids,
              #allowDuplicates: allowDuplicates,
            }),
            returnValue: _i4.Stream<_i2.ScanResult>.empty(),
          )
          as _i4.Stream<_i2.ScanResult>);

  @override
  _i4.Future<void> stopPeripheralScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopPeripheralScan, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.Peripheral createUnsafePeripheral(String? peripheralId, {String? name}) =>
      (super.noSuchMethod(
            Invocation.method(
              #createUnsafePeripheral,
              [peripheralId],
              {#name: name},
            ),
            returnValue: _FakePeripheral_4(
              this,
              Invocation.method(
                #createUnsafePeripheral,
                [peripheralId],
                {#name: name},
              ),
            ),
          )
          as _i2.Peripheral);

  @override
  _i4.Future<void> connectToPeripheral(
    String? identifier, {
    required bool? isAutoConnect,
    required int? requestMtu,
    required bool? refreshGatt,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #connectToPeripheral,
              [identifier],
              {
                #isAutoConnect: isAutoConnect,
                #requestMtu: requestMtu,
                #refreshGatt: refreshGatt,
                #timeout: timeout,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.PeripheralConnectionState> observePeripheralConnectionState(
    String? peripheralIdentifier,
    bool? emitCurrentValue,
    bool? completeOnDisconnect,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#observePeripheralConnectionState, [
              peripheralIdentifier,
              emitCurrentValue,
              completeOnDisconnect,
            ]),
            returnValue: _i4.Stream<_i2.PeripheralConnectionState>.empty(),
          )
          as _i4.Stream<_i2.PeripheralConnectionState>);

  @override
  _i4.Future<void> disconnectOrCancelPeripheralConnection(
    String? peripheralIdentifier,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectOrCancelPeripheralConnection, [
              peripheralIdentifier,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isPeripheralConnected(String? peripheralIdentifier) =>
      (super.noSuchMethod(
            Invocation.method(#isPeripheralConnected, [peripheralIdentifier]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.LogLevel> logLevel() =>
      (super.noSuchMethod(
            Invocation.method(#logLevel, []),
            returnValue: _i4.Future<_i2.LogLevel>.value(_i2.LogLevel.none),
          )
          as _i4.Future<_i2.LogLevel>);

  @override
  _i4.Future<void> setLogLevel(_i2.LogLevel? logLevel) =>
      (super.noSuchMethod(
            Invocation.method(#setLogLevel, [logLevel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Characteristic>> characteristics(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#characteristics, [peripheral, serviceUuid]),
            returnValue: _i4.Future<List<_i2.Characteristic>>.value(
              <_i2.Characteristic>[],
            ),
          )
          as _i4.Future<List<_i2.Characteristic>>);

  @override
  _i4.Future<List<_i2.Service>> services(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#services, [peripheral]),
            returnValue: _i4.Future<List<_i2.Service>>.value(<_i2.Service>[]),
          )
          as _i4.Future<List<_i2.Service>>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForPeripheral(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
    String? characteristicUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForPeripheral, [
              peripheral,
              serviceUuid,
              characteristicUuid,
            ]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForService(
    _i2.Service? service,
    String? characteristicUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForService, [
              service,
              characteristicUuid,
            ]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<List<_i2.Descriptor>> descriptorsForCharacteristic(
    _i2.Characteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#descriptorsForCharacteristic, [characteristic]),
            returnValue: _i4.Future<List<_i2.Descriptor>>.value(
              <_i2.Descriptor>[],
            ),
          )
          as _i4.Future<List<_i2.Descriptor>>);

  @override
  _i4.Future<void> discoverAllServicesAndCharacteristics(
    _i2.Peripheral? peripheral,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#discoverAllServicesAndCharacteristics, [
              peripheral,
              transactionId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Characteristic>> characteristicsForService(
    _i2.Service? service,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#characteristicsForService, [service]),
            returnValue: _i4.Future<List<_i2.Characteristic>>.value(
              <_i2.Characteristic>[],
            ),
          )
          as _i4.Future<List<_i2.Characteristic>>);

  @override
  _i4.Future<int> rssi(_i2.Peripheral? peripheral, String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#rssi, [peripheral, transactionId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> requestMtu(
    _i2.Peripheral? peripheral,
    int? mtu,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestMtu, [peripheral, mtu, transactionId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.Peripheral>> knownPeripherals(
    List<String>? peripheralIdentifiers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#knownPeripherals, [peripheralIdentifiers]),
            returnValue: _i4.Future<List<_i2.Peripheral>>.value(
              <_i2.Peripheral>[],
            ),
          )
          as _i4.Future<List<_i2.Peripheral>>);

  @override
  _i4.Future<List<_i2.Peripheral>> connectedPeripherals(
    List<String>? serviceUuids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#connectedPeripherals, [serviceUuids]),
            returnValue: _i4.Future<List<_i2.Peripheral>>.value(
              <_i2.Peripheral>[],
            ),
          )
          as _i4.Future<List<_i2.Peripheral>>);

  @override
  _i4.Future<_i5.Uint8List> readCharacteristicForIdentifier(
    _i2.Peripheral? peripheral,
    _i6.InternalCharacteristic? characteristic,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristicForIdentifier, [
              peripheral,
              characteristic,
              transactionId,
            ]),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<_i2.CharacteristicWithValue> readCharacteristicForDevice(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
    String? characteristicUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristicForDevice, [
              peripheral,
              serviceUuid,
              characteristicUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.CharacteristicWithValue>.value(
              _FakeCharacteristicWithValue_0(
                this,
                Invocation.method(#readCharacteristicForDevice, [
                  peripheral,
                  serviceUuid,
                  characteristicUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.CharacteristicWithValue>);

  @override
  _i4.Future<_i2.CharacteristicWithValue> readCharacteristicForService(
    _i2.Peripheral? peripheral,
    _i6.InternalService? service,
    String? characteristicUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristicForService, [
              peripheral,
              service,
              characteristicUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.CharacteristicWithValue>.value(
              _FakeCharacteristicWithValue_0(
                this,
                Invocation.method(#readCharacteristicForService, [
                  peripheral,
                  service,
                  characteristicUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.CharacteristicWithValue>);

  @override
  _i4.Future<void> writeCharacteristicForIdentifier(
    _i2.Peripheral? peripheral,
    _i6.InternalCharacteristic? characteristic,
    _i5.Uint8List? value,
    bool? withResponse,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeCharacteristicForIdentifier, [
              peripheral,
              characteristic,
              value,
              withResponse,
              transactionId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Characteristic> writeCharacteristicForDevice(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
    String? characteristicUuid,
    _i5.Uint8List? value,
    bool? withResponse,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeCharacteristicForDevice, [
              peripheral,
              serviceUuid,
              characteristicUuid,
              value,
              withResponse,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Characteristic>.value(
              _FakeCharacteristic_1(
                this,
                Invocation.method(#writeCharacteristicForDevice, [
                  peripheral,
                  serviceUuid,
                  characteristicUuid,
                  value,
                  withResponse,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Characteristic>);

  @override
  _i4.Future<_i2.Characteristic> writeCharacteristicForService(
    _i2.Peripheral? peripheral,
    _i6.InternalService? service,
    String? characteristicUuid,
    _i5.Uint8List? value,
    bool? withResponse,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeCharacteristicForService, [
              peripheral,
              service,
              characteristicUuid,
              value,
              withResponse,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Characteristic>.value(
              _FakeCharacteristic_1(
                this,
                Invocation.method(#writeCharacteristicForService, [
                  peripheral,
                  service,
                  characteristicUuid,
                  value,
                  withResponse,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Characteristic>);

  @override
  _i4.Stream<_i2.CharacteristicWithValue> monitorCharacteristicForDevice(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
    String? characteristicUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#monitorCharacteristicForDevice, [
              peripheral,
              serviceUuid,
              characteristicUuid,
              transactionId,
            ]),
            returnValue: _i4.Stream<_i2.CharacteristicWithValue>.empty(),
          )
          as _i4.Stream<_i2.CharacteristicWithValue>);

  @override
  _i4.Stream<_i2.CharacteristicWithValue> monitorCharacteristicForService(
    _i2.Peripheral? peripheral,
    _i6.InternalService? service,
    String? characteristicUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#monitorCharacteristicForService, [
              peripheral,
              service,
              characteristicUuid,
              transactionId,
            ]),
            returnValue: _i4.Stream<_i2.CharacteristicWithValue>.empty(),
          )
          as _i4.Stream<_i2.CharacteristicWithValue>);

  @override
  _i4.Stream<_i5.Uint8List> monitorCharacteristicForIdentifier(
    _i2.Peripheral? peripheral,
    _i6.InternalCharacteristic? characteristic,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#monitorCharacteristicForIdentifier, [
              peripheral,
              characteristic,
              transactionId,
            ]),
            returnValue: _i4.Stream<_i5.Uint8List>.empty(),
          )
          as _i4.Stream<_i5.Uint8List>);

  @override
  _i4.Future<void> writeDescriptorForIdentifier(
    _i2.Descriptor? descriptor,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForIdentifier, [
              descriptor,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptorForCharacteristic(
    _i2.Characteristic? characteristic,
    String? descriptorUuid,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForCharacteristic, [
              characteristic,
              descriptorUuid,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(#writeDescriptorForCharacteristic, [
                  characteristic,
                  descriptorUuid,
                  value,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptorForService(
    _i2.Service? service,
    String? characteristicUuid,
    String? descriptorUuid,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForService, [
              service,
              characteristicUuid,
              descriptorUuid,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(#writeDescriptorForService, [
                  service,
                  characteristicUuid,
                  descriptorUuid,
                  value,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);

  @override
  _i4.Future<_i2.Descriptor> writeDescriptorForPeripheral(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
    String? characteristicUuid,
    String? descriptorUuid,
    _i5.Uint8List? value,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeDescriptorForPeripheral, [
              peripheral,
              serviceUuid,
              characteristicUuid,
              descriptorUuid,
              value,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.Descriptor>.value(
              _FakeDescriptor_3(
                this,
                Invocation.method(#writeDescriptorForPeripheral, [
                  peripheral,
                  serviceUuid,
                  characteristicUuid,
                  descriptorUuid,
                  value,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Descriptor>);

  @override
  _i4.Future<_i5.Uint8List> readDescriptorForIdentifier(
    _i2.Descriptor? descriptor,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForIdentifier, [
              descriptor,
              transactionId,
            ]),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptorForCharacteristic(
    _i2.Characteristic? characteristic,
    String? descriptorUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForCharacteristic, [
              characteristic,
              descriptorUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(#readDescriptorForCharacteristic, [
                  characteristic,
                  descriptorUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptorForService(
    _i2.Service? service,
    String? characteristicUuid,
    String? descriptorUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForService, [
              service,
              characteristicUuid,
              descriptorUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(#readDescriptorForService, [
                  service,
                  characteristicUuid,
                  descriptorUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);

  @override
  _i4.Future<_i2.DescriptorWithValue> readDescriptorForPeripheral(
    _i2.Peripheral? peripheral,
    String? serviceUuid,
    String? characteristicUuid,
    String? descriptorUuid,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptorForPeripheral, [
              peripheral,
              serviceUuid,
              characteristicUuid,
              descriptorUuid,
              transactionId,
            ]),
            returnValue: _i4.Future<_i2.DescriptorWithValue>.value(
              _FakeDescriptorWithValue_2(
                this,
                Invocation.method(#readDescriptorForPeripheral, [
                  peripheral,
                  serviceUuid,
                  characteristicUuid,
                  descriptorUuid,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.DescriptorWithValue>);
}
